// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvvbisyuggwzkswntjkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dmJpc3l1Z2d3emtzd250amtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDg2MDMsImV4cCI6MjA2MDkyNDYwM30.j0Hv85S0Hs9hZrLXwArj1A2tMaoqdMJucmI2dtNZrrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);